name: rl2019
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - numpy=1.16.4
  - python=3.7.3
  - scipy=1.3.0
  - seaborn=0.9.0
  - tqdm=4.32.1
  - pytorch=1.2.0
  - torchvision=0.4.0
  - pyglet=1.3.2
  - pip:
    - gym==0.10.8
